/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2020-02-12 23:26:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>formulaire</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles1.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"hello\" method=\"\">\r\n");
      out.write("    \r\n");
      out.write("        <fieldset>\r\n");
      out.write("            <legend>Qui êtes-vous ?</legend>\r\n");
      out.write("\r\n");
      out.write("            <p>Les champs marqués de l'astérisque rouge sont obligatoires.</p>\r\n");
      out.write("            <p class=\"margel\">\r\n");
      out.write("                <input type=\"radio\" value=\"madame\" id=\"md\" name=\"civil\">\r\n");
      out.write("                <label for=\"md\">Madame</label>\r\n");
      out.write("                <input type=\"radio\" value=\"monsieur\" id=\"ms\" name=\"civil\">\r\n");
      out.write("                <label for=\"ms\">Monsieur</label>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"contact_nom\">Nom<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input type=\"text\" id=\"contact_nom\" name=\"NOM\" required>\r\n");
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"contact_prenom\">Prénom<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input id=\"contact_prenom\" type=\"text\" name=\"PRENOM\" required>\r\n");
      out.write("            </p>           \r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"email\">Email<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input id=\"email\" type=\"email\" name=\"EMAIL\" required>\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <p>\r\n");
      out.write("                <label for=\"selectniveau\" class=\"label\">Type d'oeuvre</label>\r\n");
      out.write("                <select id=\"selectniveau\" name=\"OEUVRE_TYPE\">\r\n");
      out.write("                    <option value=\"0\">-- Sélectionnez votre type d'oeuvre --</option>\r\n");
      out.write("                    <option value=\"bts\">Sculpture</option>\r\n");
      out.write("                    <option value=\"dut\">Peinture</option>\r\n");
      out.write("                    <option value=\"licence\">Dessin</option>\r\n");
      out.write("                    <option value=\"master\">Gravure</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </p>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <fieldset>\r\n");
      out.write("            <legend>Où habitez-vous ?</legend>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"num\">Numéro de rue</label>\r\n");
      out.write("                <input id=\"num\" type=\"text\" name=\"ADR_NUM\" size=\"4\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"rue\">Nom de rue</label>\r\n");
      out.write("                <input id=\"rue\" type=\"text\" size=\"40\" name=\"ADR_RUE\" maxlength=\"150\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"cp\">Code postal</label>\r\n");
      out.write("                <input id=\"cp\" type=\"text\" maxlength=\"5\" name=\"ADR_CODE_POSTAL\" size=\"10\" placeholder=\"5 chiffres\" pattern=\"[0-9]{5}\" title=\"nombre à 5 chiffres\">                \r\n");
      out.write("            </p>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <fieldset>\r\n");
      out.write("            <legend>Quelques informations sur l'oeuvre...</legend>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"Titre\">Titre de l'oeuvre</label>\r\n");
      out.write("                <input id=\"num\" type=\"text\" size=\"40\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"rue\">Detail technique de l'oeuvre</label>\r\n");
      out.write("                <input id=\"rue\" type=\"number\" size=\"40\" maxlength=\"150\">\r\n");
      out.write("            </p>\r\n");
      out.write("                <p>\r\n");
      out.write("                    <label class=\"Dimensions\" for=\"Dimensions\">Dimensions</label>\r\n");
      out.write("                    <input id=\"Dimensions\" type=\"number\" maxlength=\"5\" size=\"5\" placeholder=\"Cm\" pattern=\"[0-9]{5}\" title=\"Dimensions\">\r\n");
      out.write("                \r\n");
      out.write("                    <label class=\"Dimensions\" for=\"Dimensions\">x</label>\r\n");
      out.write("                    <input id=\"Dimensions\" type=\"number\" maxlength=\"5\" size=\"5\" placeholder=\"Cm\" pattern=\"[0-9]{5}\" title=\"Dimensions\">\r\n");
      out.write("                </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"prix\">Prix de vente</label>\r\n");
      out.write("                <input id=\"prix\" type=\"number\" maxlength=\"5\" size=\"5\" placeholder=\"$\" pattern=\"[0-9]{5}\" title=\"Dimensions\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"siret\">Numéro de siret</label>\r\n");
      out.write("                <input id=\"site\" type=\"text\" maxlength=\"5\" size=\"10\" placeholder=\"siret\" pattern=\"[0-9]{5}\" title=\"Dimensions\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"margel\">Disponibilité pour les gardes\r\n");
      out.write("                <input type=\"radio\" value=\"oui\" id=\"md\" name=\"civil\">\r\n");
      out.write("                <label for=\"md\">oui</label>\r\n");
      out.write("                <input type=\"radio\" value=\"non\" id=\"ms\" name=\"civil\">\r\n");
      out.write("                <label for=\"ms\">non</label>    \r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"site\">Votre site internet</label>\r\n");
      out.write("                <input id=\"site\" type=\"text\" maxlength=\"5\" size=\"40\" placeholder=\"www.VotreSite.fr\" pattern=\"[0-9]{5}\" title=\"Dimensions\">\r\n");
      out.write("            </p>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <fieldset>\r\n");
      out.write("            <legend>Des remarques ?</legend>\r\n");
      out.write("\r\n");
      out.write("            <textarea id=\"comment\" rows=\"5\" cols=\"60\" placeholder=\"La parole est à vous\"></textarea>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("        <p class=\"center\">\r\n");
      out.write("            <input type=\"submit\" value=\"Envoyer\">\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
