/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2025-01-19 15:40:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html lang=\"fr\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>INSCRIPTION SALON SAVM 2023</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles1.css\">\r\n");
      out.write("</head> \r\n");
      out.write(" <!-- Verson du 05.03 Ã  17:44 --> \r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"img-container\"> <!-- Block parent element -->\r\n");
      out.write("        <img src=banniereSAVM.jpg width=600px align=hcenter>\r\n");
      out.write("        <H2>INSCRIPTION SALON SAVM 2024</H2>\r\n");
      out.write("        <label for=\"md\">Exposition du 28 septembre au 20 octobre  2024 Ã  17h</label><BR><br>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <form action = \"helloUpload\" method = \"post\" enctype = \"multipart/form-data\" accept-charset=\"utf-8\">\r\n");
      out.write("    \r\n");
      out.write("        <fieldset>\r\n");
      out.write("            <legend>Qui Ãªtes-vous ?</legend>\r\n");
      out.write("\r\n");
      out.write("            <p>Les champs marquÃ©s de l'astÃ©risque rouge sont obligatoires.</p>\r\n");
      out.write("            <p >\r\n");
      out.write("                <label class=\"label\" for=\"civilite\">CivilitÃ©<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input type=\"radio\" value=\"Madame\" id=\"md\" name=\"CIVIL\"  required=\"required\">\r\n");
      out.write("                <label for=\"md\">Madame</label>\r\n");
      out.write("                <input type=\"radio\" value=\"Monsieur\" id=\"ms\" name=\"CIVIL\"  required=\"required\">\r\n");
      out.write("                <label for=\"ms\">Monsieur</label>                \r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"contact_nom\">Nom / Pseudo<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input type=\"text\" id=\"contact_nom\" name=\"NOM\" required>\r\n");
      out.write("                <label class=\"label\" for=\"contact_nom\">(utilisÃ© dans le catalogue)</label>\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"contact_prenom\">PrÃ©nom</label>\r\n");
      out.write("                <input id=\"contact_prenom\" type=\"text\" name=\"PRENOM\" >\r\n");
      out.write("            </p>           \r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"email\">Email<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input id=\"email\" type=\"email\" name=\"EMAIL\" required>\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"email\">Tel<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input id=\"tel\" type=\"text\" name=\"TEL\" required size=\"10\" placeholder=\"10 chiffres\"  maxlength=\"10\" pattern=\"[0-9]{10}\">\r\n");
      out.write("            </p>\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <fieldset>\r\n");
      out.write("            <legend>OÃ¹ habitez-vous ?</legend>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"num\">NumÃ©ro de rue <span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input id=\"num\" type=\"text\" name=\"ADR_NUM\" size=\"10\"  title=\"nulÃ©ro : 33 Bis par exemple\" required>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"rue\">Nom de rue<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input id=\"rue\" type=\"text\" size=\"40\" name=\"ADR_RUE\" maxlength=\"150\" required>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"cp\">Code postal<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input id=\"cp\" type=\"text\" maxlength=\"5\" name=\"ADR_CODE_POSTAL\" size=\"10\" placeholder=\"5 chiffres\" pattern=\"[0-9]{5}\" title=\"nombre Ã  5 chiffres\" required>                \r\n");
      out.write("            </p>\r\n");
      out.write("            \r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"ville\">Ville<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input id=\"cp\" type=\"text\"   onkeyup=\"this.value = this.value.toUpperCase();\" maxlength=\"30\" name=\"ADR_VILLE\" size=\"10\" placeholder=\"ville\"  title=\"ville\" required>                \r\n");
      out.write("            </p>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <fieldset>\r\n");
      out.write("            <legend>Quelques informations sur l'oeuvre (Une seule oeuvre sera prÃ©sentÃ©e)</legend>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"Titre\">Titre de l'oeuvre<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input id=\"OEUVRE_TITRE\" type=\"text\" size=\"40\" name=\"OEUVRE_TITRE\" required>\r\n");
      out.write("            </p>\r\n");
      out.write("            \r\n");
      out.write("             <p>\r\n");
      out.write("                <label for=\"selectniveau\" class=\"label\">Type d'oeuvre<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <select id=\"selectniveau\" name=\"OEUVRE_TYPE\" required>\r\n");
      out.write("                    <option value=\"0\">-- SÃ©lectionnez votre type d'oeuvre --</option>\r\n");
      out.write("                    <option value=\"Sculpture\">Sculpture</option>\r\n");
      out.write("                    <option value=\"Peinture\">Peinture</option>\r\n");
      out.write("                    <option value=\"Dessin\">Dessin</option>\r\n");
      out.write("                    <option value=\"Gravure\">Gravure</option>\r\n");
      out.write("                    <option value=\"Autres\">Autres</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </p>\r\n");
      out.write("            \r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"rue\">DÃ©crire son oeuvre </label>\r\n");
      out.write("                <textarea id=\"OEUVRE_DETAIL\" rows=\"5\" cols=\"60\" placeholder=\"Description de l'oeuvre (5 lignes max)\"  name=\"OEUVRE_DETAIL\" maxlength = \"300\"></textarea>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label  for=\"rue\">Remarques particuliÃ¨res Ã  l'exposition de l'Åuvre  </label>\r\n");
      out.write("                <textarea id=\"OEUVRE_DETAIL_EXPO\" rows=\"3\" cols=\"60\" placeholder=\"Remarques particuliÃ¨res  (3 lignes max)\"  name=\"OEUVRE_DETAIL_EXPO\" maxlength = \"180\"></textarea> \r\n");
      out.write("            </p>\r\n");
      out.write("            \r\n");
      out.write("                <p>\r\n");
      out.write("                    <label class=\"Dimensions\" for=\"Dimensions\">Dimensions Hauteur : <span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                    <input  type=\"text\" maxlength=\"4\" size=\"4\" placeholder=\"Cm\" pattern=\"[0-9]*\" title=\"Dimensions\" name=DIMENSIONY required>\r\n");
      out.write("                \r\n");
      out.write("                    <label class=\"Dimensions\" for=\"Dimensions\">x Largeur : <span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                    <input id=\"Dimensions\" type=\"text\" maxlength=\"4\" size=\"4\" placeholder=\"Cm\" pattern=\"[0-9]*\" title=\"Dimensions\"  name=DIMENSIONX required>                                        \r\n");
      out.write("                    \r\n");
      out.write("                    <label class=\"Dimensions\" for=\"Dimensions\">x Profondeur : </label>\r\n");
      out.write("                    <input id=\"Dimensions\" type=\"text\" maxlength=\"4\" size=\"4\" placeholder=\"Cm\" pattern=\"[0-9]*\" title=\"Dimensions\"  name=DIMENSIONZ >\r\n");
      out.write("                    \r\n");
      out.write("                </p>\r\n");
      out.write("                <P>\r\n");
      out.write("                    <label class=\"Dimensions\" for=\"Dimensions\">Image de l'oeuvre<span class=\"obligatoire\">*</span></label>                  \r\n");
      out.write("                    <input type = \"file\" name = \"file\" size = \"50\" required/>\r\n");
      out.write("                    <br><label class=\"Dimensions\" for=\"Dimensions\">(La qualitÃ© de l'image doit Ãªtre suffisante pour le catalogue : taille supÃ©rieure Ã  <b>1 Mo et infÃ©rieure Ã  5 Mo</b>)</label>\r\n");
      out.write("                </P>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"prix\">Prix de vente<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("                <input id=\"prix\" type=\"number\" maxlength=\"5\" size=\"5\" placeholder=\"Euros\" pattern=\"[0-9]{5}\" title=\"Dimensions\" name=\"OEUVRE_PRIX\" required> \r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"siret\">NumÃ©ro de siret</label>\r\n");
      out.write("                <input id=\"site\" type=\"text\" maxlength=\"14\" size=\"14\" placeholder=\"siret (14 Chifres)\" pattern=\"[0-9]{14}\" title=\"Dimensions\" name=\"SIRET_MDA\" >\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"margel\">ADAGP\r\n");
      out.write("                <input type=\"radio\" value=\"oui\" id=\"md1\" name=\"ADAGP\" >\r\n");
      out.write("                <label for=\"md\">oui</label>\r\n");
      out.write("                <input type=\"radio\" value=\"non\" id=\"ms1\" name=\"ADAGP\" checked>\r\n");
      out.write("                <label for=\"ms\">non</label>     \r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("\t    <!--\r\n");
      out.write("            <p class=\"margel\">DisponibilitÃ©s pour les gardes\r\n");
      out.write("                <input type=\"radio\" value=\"oui\" id=\"md1\" name=\"DISPO_GARDE\" >\r\n");
      out.write("                <label for=\"md\">oui</label>\r\n");
      out.write("                <input type=\"radio\" value=\"non\" id=\"ms1\" name=\"DISPO_GARDE\" checked>\r\n");
      out.write("                <label for=\"ms\">non</label>     \r\n");
      out.write("            </p>\r\n");
      out.write("\t    -->\r\n");
      out.write("\t    <input type=\"hidden\" value=\"non\" id=\"md1\" name=\"DISPO_GARDE\" >\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <p>\r\n");
      out.write("                <label class=\"label\" for=\"site\">Votre site internet</label>\r\n");
      out.write("                <input id=\"site\" type=\"text\" maxlength=\"50\" size=\"40\" placeholder=\"www.VotreSite.fr\"  title=\"Dimensions\" NAME=\"SITE_INTERNET\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <label class=\"label\" for=\"site\">Un mini CV (5 lignes max)</label>\r\n");
      out.write("            <textarea id=\"comment\" name=REMARQUES rows=\"5\" cols=\"60\" placeholder=\"Un mini CV (5 lignes max)\"  maxlength = \"300\" ></textarea>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <fieldset>\r\n");
      out.write("            <legend>Remarques / RÃ¨glements</legend>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <p>\r\n");
      out.write("             L'inscription sera <A style=\"text-decoration:none;color:black\"\" href=renvoiImage.jsp>dÃ©finitive</A> aprÃ¨s avoir reÃ§u le paiement (un seul chÃ¨que) (se reporter au rÃ¨glement pour participation selon le format) Ã  envoyer par courrier\r\n");
      out.write("\"SAVM Ateliers d'Art 5 ter, avenue du Bac 94210 La Varenne Saint Hilaire\" avec enveloppe de retour.\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>                \r\n");
      out.write("                <input id=\"REGLE_ADHESION\" type=\"checkbox\"  onclick='javascript:regles()'  title=\"RÃ¨gles d'adhÃ©sion\" NAME=\"REGLE_ADHESION\" required>J'ai lu, compris et acceptÃ© les rÃ¨gles d'adhÃ©sion<span class=\"obligatoire\">*</span>\r\n");
      out.write("                <A href=\"http://davic.mkdh.fr/savm-data/reglementsSAVM2023.pdf\" target=\"Reglements SAVM\"> TÃ©lÃ©chargement <img height=\"30\" width=\"30\" src=\"pdf2.png\"></A>\r\n");
      out.write("            </p>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("        <p class=\"center\">\r\n");
      out.write("            <input type=\"submit\" value=\"Envoyer\">\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function regles() {\r\n");
      out.write("    var strWindowFeatures = \"menubar=no,location=no,resizable=yes,scrollbars=yes,status=yes\";\r\n");
      out.write("    //windowObjectReference = window.open(\"http://davic.mkdh.fr/savm-data/reglementsSAVM2022.pdf\", \"Reglement SAVM 2022\", strWindowFeatures);       \r\n");
      out.write("}\r\n");
      out.write("</script> \r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
