/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2020-05-17 00:14:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class renvoiImage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>INSCRIPTION SALON SAVM 2020</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles1.css\">\r\n");
      out.write("</head>\r\n");
      out.write(" <!-- Verson du 05.03 à 17:44 -->\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"img-container\"> <!-- Block parent element -->\r\n");
      out.write("\t\t<img src=banniereSAVM.jpg width=600px align=hcenter>\r\n");
      out.write("\t\t<H2>INSCRIPTION SALON SAVM 2020</H2>\r\n");
      out.write("\t\t<label for=\"md\">Exposition du 21 Novembre au 6 Décembre 2020</label><BR><br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("    <form action = \"helloUploadRemplace\" method = \"post\" enctype = \"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("        <fieldset>\r\n");
      out.write("            <legend>Renvoi de l'image de l'oeuvre</legend>\r\n");
      out.write("            \r\n");
      out.write("\t            <p>\r\n");
      out.write("\t                <label class=\"label\" for=\"ID\">ID<span class=\"obligatoire\">*</span></label>\r\n");
      out.write("\t                <input id=\"oldIdPost\" type=\"text\" name=\"oldIdPost\" required size=\"10\" placeholder=\"ID : YYYYMMDD_HHMiSS\"  maxlength=\"15\" pattern=\"[0-9]{8}_[0-9]{6}\">\r\n");
      out.write("\t            </p>\r\n");
      out.write("            \r\n");
      out.write("                <P>\r\n");
      out.write("                \t<label class=\"Dimensions\" for=\"Dimensions\">Image de l'oeuvre<span class=\"obligatoire\">*</span></label>                \t\r\n");
      out.write("                    <input type = \"file\" name = \"file\" size = \"50\" required/>\r\n");
      out.write("                    <br><label class=\"Dimensions\" for=\"Dimensions\">(La qualité de l'image doit être suffisante pour le catalogue : taille supérieure à <b>1 Mo et inférieure à 5 Mo</b>)</label>\r\n");
      out.write("                </P>\r\n");
      out.write("         \r\n");
      out.write("        </fieldset>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("        <p class=\"center\">\r\n");
      out.write("            <input type=\"submit\" value=\"Envoyer\">\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
